CREATE DATABASE IF NOT EXISTS ocotocorp_app;
USE ocotocorp_app;

-- 1. USER Table
CREATE TABLE USER (
    uuid UUID PRIMARY KEY DEFAULT UUID(),
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    password_salt VARCHAR(255),
    last_seen DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. ROLE Table
CREATE TABLE ROLE (
    uuid UUID PRIMARY KEY DEFAULT UUID(),
    name VARCHAR(100) NOT NULL,
    permissions_mask INT DEFAULT 0
);

-- 3. CHANNEL Table
CREATE TABLE CHANNEL (
    uuid UUID PRIMARY KEY DEFAULT UUID(),
    title VARCHAR(255) NOT NULL,
    owner_id UUID,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_channel_owner FOREIGN KEY (owner_id) REFERENCES USER(uuid) ON DELETE SET NULL
);

-- 4. DIRECT_MESSAGE Table
CREATE TABLE DIRECT_MESSAGE (
    uuid UUID PRIMARY KEY DEFAULT UUID(),
    sender_id UUID NOT NULL,
    recipient_id UUID NOT NULL,
    content TEXT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    seen_at DATETIME,
    CONSTRAINT fk_dm_sender FOREIGN KEY (sender_id) REFERENCES USER(uuid) ON DELETE CASCADE,
    CONSTRAINT fk_dm_recipient FOREIGN KEY (recipient_id) REFERENCES USER(uuid) ON DELETE CASCADE
);

-- 5. CHANNEL_MESSAGE Table
CREATE TABLE CHANNEL_MESSAGE (
    uuid UUID PRIMARY KEY DEFAULT UUID(),
    channel_id UUID NOT NULL,
    sender_id UUID NOT NULL,
    content TEXT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cm_channel FOREIGN KEY (channel_id) REFERENCES CHANNEL(uuid) ON DELETE CASCADE,
    CONSTRAINT fk_cm_sender FOREIGN KEY (sender_id) REFERENCES USER(uuid) ON DELETE CASCADE
);

-- 6. USER_ROLES (Junction Table)
CREATE TABLE USER_ROLES (
    uuid UUID PRIMARY KEY DEFAULT UUID(),
    user_id UUID NOT NULL,
    role_id UUID NOT NULL,
    CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES USER(uuid) ON DELETE CASCADE,
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES ROLE(uuid) ON DELETE CASCADE
);

-- 7. CHANNEL_ROLES (Junction Table)
CREATE TABLE CHANNEL_ROLES (
    uuid UUID PRIMARY KEY DEFAULT UUID(),
    channel_id UUID NOT NULL,
    role_id UUID NOT NULL,
    CONSTRAINT fk_cr_channel FOREIGN KEY (channel_id) REFERENCES CHANNEL(uuid) ON DELETE CASCADE,
    CONSTRAINT fk_cr_role FOREIGN KEY (role_id) REFERENCES ROLE(uuid) ON DELETE CASCADE
);

-- 8. CHANNEL_MESSAGE_SEEN (Junction Table for Read Receipts)
CREATE TABLE CHANNEL_MESSAGE_SEEN (
    uuid UUID PRIMARY KEY DEFAULT UUID(),
    message_id UUID NOT NULL,
    user_id UUID NOT NULL,
    seen_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cms_message FOREIGN KEY (message_id) REFERENCES CHANNEL_MESSAGE(uuid) ON DELETE CASCADE,
    CONSTRAINT fk_cms_user FOREIGN KEY (user_id) REFERENCES USER(uuid) ON DELETE CASCADE
);